### ISSUE TITLE
UberJar not working

### ISSUE THREAD

**Issue by theapache64** [theapache64/stackzy#41]
**Describe the bug**

I've downloaded `Stackzy-linux-x64-1.0.0.jar` from the releases `(v1.0.0-beta03)` and executed with `java -jar Stackzy-linux-x64-1.0.0.jar`, but am getting below error

<details>
<summary>Crashlog</summary>

```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
	at java.base/sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:335)
	at java.base/sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:268)
	at java.base/java.util.jar.JarVerifier.processEntry(JarVerifier.java:273)
	at java.base/java.util.jar.JarVerifier.update(JarVerifier.java:230)
	at java.base/java.util.jar.JarFile.initializeVerifier(JarFile.java:759)
	at java.base/java.util.jar.JarFile.ensureInitialization(JarFile.java:1038)
	at java.base/java.util.jar.JavaUtilJarAccessImpl.ensureInitialization(JavaUtilJarAccessImpl.java:69)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader$2.getManifest(URLClassPath.java:873)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:807)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:719)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:642)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:600)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:427)
	at java.base/sun.launcher.LauncherHelper.loadMainClass(LauncherHelper.java:760)
	at java.base/sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:655)

```
</details>

**To Reproduce**
1. Download any uberjar from [here](https://github.com/theapache64/stackzy/releases/tag/v1.0.0-beta03)
2. Execute it using `java -jar Stackzy-*.jar`

**Expected behavior**
Should launch Stackzy window

**Screenshots**

![image](https://user-images.githubusercontent.com/9678279/111250496-6d4aba00-8633-11eb-8257-8a19d65a4599.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Stackzy Version: `v1.0.0-beta03`

**Additional context**

**Comment by theapache64** [comment]
Could be helpful : https://stackoverflow.com/a/14441628/4370279

**Comment by mikepenz** [comment]
we use the jar bundling from compose desktop here. https://github.com/theapache64/stackzy/blob/master/.github/workflows/ci.yml#L112 

```
packageUberJarForCurrentOS
```

maybe something changed for linux? it used to work on mac at least

**Comment by mikepenz** [comment]
Double checked. no longer works for mac either.

**Comment by theapache64** [comment]
@mikepenz Probably because of the library we recently added :thinking:

**Comment by letroll** [comment]
no longer works for windows either.

**Comment by theapache64** [comment]
@letroll thanks for the feedback. am planning to work on this issue this weekend.

**Comment by theapache64** [comment]
@letroll Please try [this](https://github.com/theapache64/stackzy/releases/tag/v1.0.0-beta05) release. Feel free to reopen this issue if it still exists.

**Comment by letroll** [comment]
Sorry but not better with this deliverable

**Comment by theapache64** [comment]
@letroll Ohh.. forgot to mention,  you need Java 15 to run Stackzy via uber-jar. However, this is not a problem if you can try Stackzy by installing the `msi` version (Windows) or `deb` (Linux).
