### ISSUE TITLE
Facebook fails to decompile

### ISSUE THREAD

**Issue by theapache64** [theapache64/stackzy#77]
**Stacktrace**

```
java.nio.file.NoSuchFileException: /var/folders/6z/gn1r_7j10kx40bb7r_78gz5r0000gp/T/stackzy/com.facebook.katana/AndroidManifest.xml
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:375)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:426)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
	at java.base/java.nio.file.Files.newInputStream(Files.java:160)
	at kotlin.io.path.PathsKt__PathReadWriteKt.readText(PathReadWrite.kt:155)
	at kotlin.io.path.PathsKt__PathReadWriteKt.readText$default(PathReadWrite.kt:154)
	at com.theapache64.stackzy.data.repo.ApkAnalyzerRepo.getAppNameLabel(ApkAnalyzerRepo.kt:211)
	at com.theapache64.stackzy.data.repo.ApkAnalyzerRepo.getAppName(ApkAnalyzerRepo.kt:164)
	at com.theapache64.stackzy.data.repo.ApkAnalyzerRepo$analyze$2.invokeSuspend(ApkAnalyzerRepo.kt:46)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

## Output

![image](https://user-images.githubusercontent.com/9678279/138524826-59326d24-9407-40d4-a7fd-d5b90e92d4f4.png)

**Comment by theapache64** [comment]
Same for JioCinema
