### ISSUE TITLE
Mac OS JAVA_HOME env variable not found error

### ISSUE THREAD

**Issue by AddictArts** [theapache64/stackzy#82]
Build the app with JDK15, run it and get the error message.

**Comment by theapache64** [comment]
Can you enter the command `java -version` in your terminal and paste the output here?

**Comment by SteinerOk** [comment]
I try to launch stackzy on MacOS 12.1, but receive this error:

![image](https://user-images.githubusercontent.com/9264077/148647239-fde36d87-0c05-45ed-9edd-f28d5b8117cf.png)

**Comment by rickclephas** [comment]
I am not quite sure yet where the `JAVA_HOME` should be set for this to work automatically but you can open the app with the following command:
```
JAVA_HOME=$(/usr/libexec/java_home -v 15) open /path/to/Stackzy.app
```

**Comment by theapache64** [comment]
I think you've JDK installed, but `JAVA_HOME` is not set. Maybe I shouldn't rely on `JAVA_HOME` at all. 
https://github.com/theapache64/stackzy/blob/49811525fa0ee7d737774784ec0015878ba06721/src/main/kotlin/com/theapache64/stackzy/ui/feature/splash/SplashViewModel.kt#L68-L75

@SteinerOk Can you enter `echo $JAVA_HOME` in your terminal?

**Comment by theapache64** [comment]
@SteinerOk @AddictArts Can you guys take a pull from `master` and try run `./gradlew run` now? I've made some changes

**Comment by SteinerOk** [comment]
@theapache64, you are right :(
![image](https://user-images.githubusercontent.com/9264077/148656058-4c1c01a2-84b6-449a-b3ad-9a1fc45394c2.png)

**Comment by SteinerOk** [comment]
@theapache64 I launched via `JAVA_HOME=$(/usr/libexec/java_home -v 15) open /path/to/Stackzy.app`, but got new error:
![image](https://user-images.githubusercontent.com/9264077/148656213-dd934beb-0d3e-43f5-b1d4-b865d156483a.png)

**Comment by rickclephas** [comment]
> I think you've JDK installed, but JAVA_HOME is not set. Maybe I shouldn't rely on JAVA_HOME at all.

Even with `JAVA_HOME` set in `~/.zshenv`, `~/.zshrc` or `~/.zprofile` I got the same error.
Maybe it should be set somewhere else for it to affect applications as well?

> Can you guys take a pull from `master` and try run `./gradlew run` now? I've made some changes

I am seeing #80 when running `./gradlew run`. 
However `./gradlew createDistributable` does create the app which no longer shows the error message 👍🏻 .

**Comment by theapache64** [comment]
@rickclephas Interesting. 
I've created an uberJar for macOS. Can you guys download this [jar](https://drive.google.com/file/d/11s1AT6SPU3872Zjq4yeEk8e_Q8vssNfh/view?usp=sharing) and run `java -jar /path/to/jar` ?

@rickclephas @SteinerOk @AddictArts

**Comment by rickclephas** [comment]
@theapache64 I am using macOS 12.1 (MBP M1 Pro) with JDK 15 (Azul) and get the following error with that jar:
```
Caused by: org.jetbrains.skiko.LibraryLoadException: Cannot find libskiko-macos-arm64.dylib.sha256, proper native dependency missing.
	at org.jetbrains.skiko.Library.load(Library.kt:72)
	at org.jetbrains.skia.impl.Library$Companion.staticLoad(Library.jvm.kt:12)
	at org.jetbrains.skia.Image.<clinit>(Image.kt:144)
```

**Comment by theapache64** [comment]
@rickclephas Ohh you're using the M1. That needs a separate binary I guess.
