### ISSUE TITLE
Google Authentication Related Feature does not work

### ISSUE THREAD

**Issue by wiryadev** [theapache64/stackzy#96]
**Login**
When i tried to login, it shows snackbar with message "NeedsBrowser".
![image](https://user-images.githubusercontent.com/26060382/169328241-a54e6c93-5d88-48df-a9df-8e55c7717ea2.png)
Then i check the logcat and it  shows this log.
![image](https://user-images.githubusercontent.com/26060382/169328141-ca259251-92e6-4659-ba32-b02a9d34aae9.png)

**Register**
When i tried to register, the link that i got redirected at gives 404 error.
![image](https://user-images.githubusercontent.com/26060382/169328611-cd8c06d1-520e-41e2-86f2-ade6edde0f86.png)

Additional Info:
Tested both with released .msi in version `1.2.3` and the current `master` branch which built using IntelliJ. I am using Windows 11.

**Comment by smascaro** [comment]
I'm facing it aswell. Just make the `/Signup` in the URL lowercase (`/signup`) and it will open the google account creation page.

**Comment by paolorotolo** [comment]
Same issue on MacOS Ventura (M2 Pro):
```
org.apache.http.client.ClientProtocolException: NeedsBrowser
	at com.akdeniz.googleplaycrawler.Identity.doPost(Identity.java:181)
	at com.akdeniz.googleplaycrawler.Identity.signIn(Identity.java:142)
	at com.akdeniz.googleplaycrawler.GooglePlayAPI.login(GooglePlayAPI.java:319)
	at com.github.theapache64.gpa.api.Play$login$2.invokeSuspend(Play.kt:39)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by theapache64** [comment]
The problem with the registration link has been resolved will be accessible in the upcoming version.
The login problem may be due to the 2FA feature. Do you guys have 2FA enabled?

**Comment by alexstyl** [comment]
Same issue. Not using a 2FA
